#!/bin/sh
if ! whoami &> /dev/null; then
  if [ -w /etc/passwd ]; then
    echo "${USER_NAME:-ubuntu}:x:$(id -u):1001:${USER_NAME:-ubuntu} user:/home/${USER_NAME:-ubuntu}:/bin/bash" >> /etc/passwd
  fi
fi
exec "$@"
